### ISSUE TITLE
关于{!!  !!} 不起作用

### ISSUE THREAD

**Issue by lwt33713803** [terranc/think-blade#2]
我想输入 分页标签内容；刚开始使用{{ }}会讲html源码输出到页面；使用{!!  !!} 的话会连同标签整个输出；
 
![a0db163e-498d-422f-9372-8ca46f2f1912](https://user-images.githubusercontent.com/12270339/29500252-924d94b6-8651-11e7-85b5-660c50eaa2a4.png)
页面输出如下：
![7bb3e913-2358-454f-aec9-46cae222a3b1](https://user-images.githubusercontent.com/12270339/29500275-cf177ae2-8651-11e7-9c68-f2dbcf3fc1c4.png)

**Comment by terranc** [comment]
是的，有这个问题，急着用的话，有兴趣可以PR，我最近项目紧，暂时没时间来弄，不好意思。

**Comment by terranc** [comment]
可以考虑用 php 标签

**Comment by lwt33713803** [comment]
找到原因了，配置文件结束标签写错了！！--
![default](https://user-images.githubusercontent.com/12270339/29610648-78675a04-882d-11e7-8167-f65e0551a38a.png)
