### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by wvfeng** [terranc/think-blade#4]
`protected $config = [
        // 视图基础目录（集中式）
        'view_base'   => '',
        // 是否开启模板编译缓存,设为false则每次都会重新编译
        'tpl_cache'          => true,
        // 模板起始路径
        'view_path'   => '',
        'tpl_begin'   => '{{',
        'tpl_end'   => '}}',
        'tpl_raw_begin'   => '{!!',
        'tpl_raw_end'   => '!!}',
        // 模板缓存目录
        'view_cache_path'   => RUNTIME_PATH . 'temp' . DS,
        // 模板文件后缀
        'view_suffix' => 'blade.php',
        'tpl_replace_string'=>''
    ];`
这段代码中‘view_cache_path’这个配置在php5.4.45中是不支持拼接常量的
虽然不清楚这个配置是干嘛的‘tpl_replace_string’，但是少了他会报错。我的是thinkPHP5.0

**Comment by terranc** [comment]
请使用php5.6以上版本，低版本只能自行找对应解决方案了

**Comment by wvfeng** [comment]
已经找到解决方案

发送自 Windows 10 版邮件应用

发件人: Terran
发送时间: 2018年6月4日 13:13
收件人: terranc/think-blade
抄送: wvfeng; Author
主题: Re: [terranc/think-blade] 兼容性问题 (#4)

请使用php5.6以上版本，低版本只能自行找对应解决方案了
